import { CreatePetInput } from 'src/schema/pet.schema';

export const pets: CreatePetInput['body'][] = [
  {
    name: 'Buddy',
    breed: 'Golden Retriever',
    status: 'AVAILABLE',
    age: '12',
    birthDate: '2022',
    description: 'dog',
    tags: ['dog'],
    photoUrl: 'https://images.unsplash.com/photo-1560807707-8cc777a4d2f9',
  },
  {
    name: 'Mittens',
    breed: 'Siamese',
    status: 'ADOPTED',
    age: '12',
    birthDate: '2022',
    description: 'dog',
    tags: ['dog'],
    photoUrl: 'https://images.unsplash.com/photo-1592194996308-7d9c3f8d4a2b',
  },
  {
    name: 'Charlie',
    breed: 'Labrador Retriever',
    status: 'AVAILABLE',
    age: '12',
    birthDate: '2022',
    description: 'dog',
    tags: ['dog'],
    photoUrl: 'https://images.unsplash.com/photo-1517423440428-a5a00ad493e8',
  },
  {
    name: 'Whiskers',
    breed: 'Maine Coon',
    status: 'PENDING',
    age: '12',
    birthDate: '2022',
    description: 'dog',
    tags: ['dog'],
    photoUrl: 'https://images.unsplash.com/photo-1560807707-8cc777a4d2f9',
  },
  {
    name: 'Max',
    breed: 'Beagle',
    status: 'ADOPTED',
    age: '12',
    birthDate: '2022',
    description: 'dog',
    tags: ['dog'],
    photoUrl: 'https://images.unsplash.com/photo-1558788353-f76d92427f16',
  },
  {
    name: 'Luna',
    breed: 'Bengal',
    status: 'AVAILABLE',
    age: '12',
    birthDate: '2022',
    description: 'dog',
    tags: ['dog'],
    photoUrl: 'https://images.unsplash.com/photo-1592194996308-7d9c3f8d4a2b',
  },
];
