name: e2e staging
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'
jobs:
  e2e-staging:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

    name: e2e-staging
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Install
        uses: ./.github/actions/install

      - name: pnpm db:generate
        run: pnpm db:generate
        shell: bash

      - name: e2e staging
        uses: ./.github/actions/e2e
        with:
          target: e2e-staging
